@startuml "use-cases"
left to right direction
actor Cliente as c
actor Admin as a
actor Vendedor as v
package Casos-de-Uso{
  usecase "Vizualisar Produtos" as UCc1
  usecase "Acessar Carrinho" as UCc2
  usecase "Pesquisar Produtos" as UCc4
  usecase "Cancelar Compra" as UCc5
  usecase "Realizar o Pagamento" as UCc6
  usecase "Ver Ofertas" as UCc7
  usecase "Avaliar Produtos" as UCc8
  usecase "Acessar Produto" as UCc9
  usecase "Definir Endereço" as UCc10
  usecase "Ver Histórico de Compras" as UCc11

  usecase "Visualizar Clientes" as UCa1
  usecase "Visualizar Lucro" as UCa2
  usecase "Visualizar Vendedores" as UCa3

  usecase "Colocar produtos para venda" as UCv1
  usecase "Visualizar produtos a venda" as UCv2
  usecase "Visualizar produtos vendidos" as UCv3

}
c --> UCc1
c --> UCc2
c --> UCc4
c --> UCc5
c --> UCc6
c --> UCc7
c --> UCc8
c --> UCc9
c --> UCc10
c --> UCc11
a --> UCa1
a --> UCa2
a --> UCa3
v --> UCv1
v --> UCv2
v --> UCv3
@enduml
